/**
 * Canonical SAT-Core authentication protocol master registry (20 protocols).
 * Seeded into `SatProtocol`; admin may tune weights/active/URLs without re-seed overwriting those fields.
 */

export type SatProtocolRegistryEntry = {
  displayOrder: number;
  protocolCode: string;
  protocolSlug: string;
  protocolName: string;
  protocolCategory: string;
  shortDescription: string;
  longDescription: string;
  securityClassification: string;
  trustLevel: number;
  riskReductionScore: number;
  iconKey: string;
  colorTheme: string;
  flagEnterprise: boolean;
  flagGovernment: boolean;
  flagTelco: boolean;
  flagConsumer: boolean;
  flagAiAgent: boolean;
  globalAvailability: boolean;
  apiReady: boolean;
  auditRequired: boolean;
  consentRequired: boolean;
  zeroKnowledgeCompatible: boolean;
  simOrEsimRequired: boolean;
  deviceBindingRequired: boolean;
};

/** Feed weight default; home/roam split defaults to 40/60 (100%) for H/R display. */
export const SAT_PROTOCOL_DEFAULT_WEIGHT = 60;
export const SAT_PROTOCOL_DEFAULT_HOME = 40;
export const SAT_PROTOCOL_DEFAULT_ROAMING = 60;

export const SAT_PROTOCOL_REGISTRY: SatProtocolRegistryEntry[] = [
  {
    displayOrder: 1,
    protocolCode: "SAT-ID",
    protocolSlug: "sat-id",
    protocolName: "SAT-ID",
    protocolCategory: "Identity",
    shortDescription: "Binds user, device, SIM/eSIM, account, and agent identity across SAT-Core.",
    longDescription:
      "SAT-ID establishes cryptographically verifiable identity anchors for subscribers, devices, secure elements, and autonomous agents. It is the root trust vector for downstream SAT protocols and supports cross-domain correlation under policy.",
    securityClassification: "CRITICAL",
    trustLevel: 5,
    riskReductionScore: 88,
    iconKey: "sat-core-id",
    colorTheme: "sky",
    flagEnterprise: true,
    flagGovernment: true,
    flagTelco: true,
    flagConsumer: true,
    flagAiAgent: true,
    globalAvailability: true,
    apiReady: true,
    auditRequired: true,
    consentRequired: true,
    zeroKnowledgeCompatible: true,
    simOrEsimRequired: true,
    deviceBindingRequired: true,
  },
  {
    displayOrder: 2,
    protocolCode: "SAT-AUTH",
    protocolSlug: "sat-auth",
    protocolName: "SAT-AUTH",
    protocolCategory: "Authentication",
    shortDescription: "Cryptographic authentication replacing passwords and SMS OTP.",
    longDescription:
      "SAT-AUTH delivers phishing-resistant, SIM- and secure-element aware authentication using SAT-Core credentials instead of shared secrets. It aligns with zero-trust access patterns for enterprise, telco, and consumer surfaces.",
    securityClassification: "CRITICAL",
    trustLevel: 5,
    riskReductionScore: 92,
    iconKey: "sat-core-auth",
    colorTheme: "emerald",
    flagEnterprise: true,
    flagGovernment: true,
    flagTelco: true,
    flagConsumer: true,
    flagAiAgent: true,
    globalAvailability: true,
    apiReady: true,
    auditRequired: true,
    consentRequired: true,
    zeroKnowledgeCompatible: true,
    simOrEsimRequired: false,
    deviceBindingRequired: true,
  },
  {
    displayOrder: 3,
    protocolCode: "SAT-CONSENT",
    protocolSlug: "sat-consent",
    protocolName: "SAT-CONSENT",
    protocolCategory: "Authorization",
    shortDescription: "Permissioned user authorization for every sensitive action.",
    longDescription:
      "SAT-CONSENT records explicit, revocable consent tied to identity and context. It powers regulated workflows (payments, data export, AI actions) with machine-readable policy proofs and audit linkage.",
    securityClassification: "HIGH",
    trustLevel: 5,
    riskReductionScore: 85,
    iconKey: "sat-core-consent",
    colorTheme: "violet",
    flagEnterprise: true,
    flagGovernment: true,
    flagTelco: true,
    flagConsumer: true,
    flagAiAgent: true,
    globalAvailability: true,
    apiReady: true,
    auditRequired: true,
    consentRequired: true,
    zeroKnowledgeCompatible: true,
    simOrEsimRequired: false,
    deviceBindingRequired: false,
  },
  {
    displayOrder: 4,
    protocolCode: "SAT-MFA",
    protocolSlug: "sat-mfa",
    protocolName: "SAT-MFA",
    protocolCategory: "Authentication",
    shortDescription: "Hardware and SIM-rooted multi-factor authentication.",
    longDescription:
      "SAT-MFA composes possession (SIM/eSIM, secure element), device posture, and policy signals into tiered assurance levels suitable for high-value transactions and sovereign workloads.",
    securityClassification: "CRITICAL",
    trustLevel: 5,
    riskReductionScore: 90,
    iconKey: "sat-core-mfa",
    colorTheme: "amber",
    flagEnterprise: true,
    flagGovernment: true,
    flagTelco: true,
    flagConsumer: true,
    flagAiAgent: false,
    globalAvailability: true,
    apiReady: true,
    auditRequired: true,
    consentRequired: true,
    zeroKnowledgeCompatible: false,
    simOrEsimRequired: true,
    deviceBindingRequired: true,
  },
  {
    displayOrder: 5,
    protocolCode: "SAT-SESSION",
    protocolSlug: "sat-session",
    protocolName: "SAT-SESSION",
    protocolCategory: "Session Management",
    shortDescription: "Trusted session creation, renewal, expiration, and revocation.",
    longDescription:
      "SAT-SESSION governs session tokens bound to device and subscriber context, supporting graceful rotation, risk-based shortening, and immediate kill switches across channels.",
    securityClassification: "HIGH",
    trustLevel: 4,
    riskReductionScore: 78,
    iconKey: "sat-core-session",
    colorTheme: "cyan",
    flagEnterprise: true,
    flagGovernment: true,
    flagTelco: true,
    flagConsumer: true,
    flagAiAgent: true,
    globalAvailability: true,
    apiReady: true,
    auditRequired: true,
    consentRequired: false,
    zeroKnowledgeCompatible: false,
    simOrEsimRequired: false,
    deviceBindingRequired: true,
  },
  {
    displayOrder: 6,
    protocolCode: "SAT-DEVICE",
    protocolSlug: "sat-device",
    protocolName: "SAT-DEVICE",
    protocolCategory: "Device Security",
    shortDescription: "Device fingerprinting and SIM/eSIM secure-element verification.",
    longDescription:
      "SAT-DEVICE attests hardware integrity, OS posture, and secure-element presence. It reduces account takeover by binding sessions and credentials to trusted device profiles.",
    securityClassification: "HIGH",
    trustLevel: 4,
    riskReductionScore: 82,
    iconKey: "sat-core-device",
    colorTheme: "slate",
    flagEnterprise: true,
    flagGovernment: true,
    flagTelco: true,
    flagConsumer: true,
    flagAiAgent: false,
    globalAvailability: true,
    apiReady: true,
    auditRequired: true,
    consentRequired: true,
    zeroKnowledgeCompatible: false,
    simOrEsimRequired: true,
    deviceBindingRequired: true,
  },
  {
    displayOrder: 7,
    protocolCode: "SAT-AGENT",
    protocolSlug: "sat-agent",
    protocolName: "SAT-AGENT",
    protocolCategory: "AI Security",
    shortDescription: "Authorized AI agent identity, role, scope, and action limits.",
    longDescription:
      "SAT-AGENT issues scoped credentials for autonomous agents with least-privilege policies, human-in-the-loop gates, and immutable action logs aligned to enterprise and regulatory AI governance.",
    securityClassification: "HIGH",
    trustLevel: 4,
    riskReductionScore: 80,
    iconKey: "sat-core-agent",
    colorTheme: "fuchsia",
    flagEnterprise: true,
    flagGovernment: true,
    flagTelco: true,
    flagConsumer: false,
    flagAiAgent: true,
    globalAvailability: true,
    apiReady: true,
    auditRequired: true,
    consentRequired: true,
    zeroKnowledgeCompatible: false,
    simOrEsimRequired: false,
    deviceBindingRequired: false,
  },
  {
    displayOrder: 8,
    protocolCode: "SAT-API",
    protocolSlug: "sat-api",
    protocolName: "SAT-API",
    protocolCategory: "API Security",
    shortDescription: "Secure REST and GraphQL access with SAT-bound tokens.",
    longDescription:
      "SAT-API wraps service interfaces with mutual authentication, audience-scoped tokens, and continuous verification hooks so integrations inherit SAT trust without bespoke PKI per partner.",
    securityClassification: "HIGH",
    trustLevel: 4,
    riskReductionScore: 76,
    iconKey: "sat-core-api",
    colorTheme: "indigo",
    flagEnterprise: true,
    flagGovernment: true,
    flagTelco: true,
    flagConsumer: true,
    flagAiAgent: true,
    globalAvailability: true,
    apiReady: true,
    auditRequired: true,
    consentRequired: false,
    zeroKnowledgeCompatible: false,
    simOrEsimRequired: false,
    deviceBindingRequired: false,
  },
  {
    displayOrder: 9,
    protocolCode: "SAT-EVENT",
    protocolSlug: "sat-event",
    protocolName: "SAT-EVENT",
    protocolCategory: "Event Architecture",
    shortDescription: "Authenticated events for login, payment, approval, permit, handoff, and comms.",
    longDescription:
      "SAT-EVENT normalizes high-value domain events with signatures, replay protection, and correlation IDs spanning CRM, billing, government permits, and AI-mediated workflows.",
    securityClassification: "STANDARD",
    trustLevel: 4,
    riskReductionScore: 72,
    iconKey: "sat-core-event",
    colorTheme: "teal",
    flagEnterprise: true,
    flagGovernment: true,
    flagTelco: true,
    flagConsumer: true,
    flagAiAgent: true,
    globalAvailability: true,
    apiReady: true,
    auditRequired: true,
    consentRequired: true,
    zeroKnowledgeCompatible: false,
    simOrEsimRequired: false,
    deviceBindingRequired: false,
  },
  {
    displayOrder: 10,
    protocolCode: "SAT-AUDIT",
    protocolSlug: "sat-audit",
    protocolName: "SAT-AUDIT",
    protocolCategory: "Audit & Compliance",
    shortDescription: "Immutable audit logging for every user, system, and AI action.",
    longDescription:
      "SAT-AUDIT captures append-only evidence chains with hash chaining and retention policies suitable for financial, healthcare, and sovereign compliance frameworks.",
    securityClassification: "SOVEREIGN",
    trustLevel: 5,
    riskReductionScore: 86,
    iconKey: "sat-core-audit",
    colorTheme: "stone",
    flagEnterprise: true,
    flagGovernment: true,
    flagTelco: true,
    flagConsumer: true,
    flagAiAgent: true,
    globalAvailability: true,
    apiReady: true,
    auditRequired: true,
    consentRequired: true,
    zeroKnowledgeCompatible: false,
    simOrEsimRequired: false,
    deviceBindingRequired: false,
  },
  {
    displayOrder: 11,
    protocolCode: "SAT-PAY",
    protocolSlug: "sat-pay",
    protocolName: "SAT-PAY",
    protocolCategory: "Payments",
    shortDescription: "Authenticated payments, billing events, chargeback defense, and consent proof.",
    longDescription:
      "SAT-PAY binds payment instruments and authorization proofs to SAT identity and consent artifacts, improving dispute resolution and reducing synthetic fraud.",
    securityClassification: "CRITICAL",
    trustLevel: 5,
    riskReductionScore: 89,
    iconKey: "sat-core-pay",
    colorTheme: "lime",
    flagEnterprise: true,
    flagGovernment: true,
    flagTelco: true,
    flagConsumer: true,
    flagAiAgent: false,
    globalAvailability: true,
    apiReady: true,
    auditRequired: true,
    consentRequired: true,
    zeroKnowledgeCompatible: false,
    simOrEsimRequired: false,
    deviceBindingRequired: true,
  },
  {
    displayOrder: 12,
    protocolCode: "SAT-CRM",
    protocolSlug: "sat-crm",
    protocolName: "SAT-CRM",
    protocolCategory: "CRM Security",
    shortDescription: "Secure customer, lead, support, and relationship management.",
    longDescription:
      "SAT-CRM enforces verified identities for CRM actors, masks sensitive attributes by policy, and propagates SAT consent into marketing and support automation.",
    securityClassification: "STANDARD",
    trustLevel: 3,
    riskReductionScore: 68,
    iconKey: "sat-core-crm",
    colorTheme: "blue",
    flagEnterprise: true,
    flagGovernment: false,
    flagTelco: true,
    flagConsumer: true,
    flagAiAgent: true,
    globalAvailability: true,
    apiReady: true,
    auditRequired: true,
    consentRequired: true,
    zeroKnowledgeCompatible: false,
    simOrEsimRequired: false,
    deviceBindingRequired: false,
  },
  {
    displayOrder: 13,
    protocolCode: "SAT-KYC-KYB",
    protocolSlug: "sat-kyc-kyb",
    protocolName: "SAT-KYC/KYB",
    protocolCategory: "Identity Verification",
    shortDescription: "Reusable verified identity for humans, businesses, and institutions.",
    longDescription:
      "SAT-KYC/KYB packages attestations and document checks into portable trust bundles that downstream SAT protocols can consume without re-collecting raw PII.",
    securityClassification: "HIGH",
    trustLevel: 5,
    riskReductionScore: 84,
    iconKey: "sat-core-kyc",
    colorTheme: "orange",
    flagEnterprise: true,
    flagGovernment: true,
    flagTelco: true,
    flagConsumer: true,
    flagAiAgent: false,
    globalAvailability: true,
    apiReady: true,
    auditRequired: true,
    consentRequired: true,
    zeroKnowledgeCompatible: true,
    simOrEsimRequired: false,
    deviceBindingRequired: false,
  },
  {
    displayOrder: 14,
    protocolCode: "SAT-CREDENTIAL",
    protocolSlug: "sat-credential",
    protocolName: "SAT-CREDENTIAL",
    protocolCategory: "Credential Security",
    shortDescription: "Cryptographic credentials in SIM/eSIM, secure element, smart card, or wallet.",
    longDescription:
      "SAT-CREDENTIAL manages issuance, rotation, and revocation of asymmetric keys and W3C-aligned credentials anchored to hardware roots available to the subscriber profile.",
    securityClassification: "CRITICAL",
    trustLevel: 5,
    riskReductionScore: 91,
    iconKey: "sat-core-credential",
    colorTheme: "rose",
    flagEnterprise: true,
    flagGovernment: true,
    flagTelco: true,
    flagConsumer: true,
    flagAiAgent: false,
    globalAvailability: true,
    apiReady: true,
    auditRequired: true,
    consentRequired: true,
    zeroKnowledgeCompatible: true,
    simOrEsimRequired: true,
    deviceBindingRequired: true,
  },
  {
    displayOrder: 15,
    protocolCode: "SAT-DATA",
    protocolSlug: "sat-data",
    protocolName: "SAT-DATA",
    protocolCategory: "Data Governance",
    shortDescription: "Permissioned data access, retention, minimization, and sharing.",
    longDescription:
      "SAT-DATA applies purpose limitation, jurisdiction-aware residency, and cryptographic envelopes so analytics and AI training respect subscriber intent and law.",
    securityClassification: "HIGH",
    trustLevel: 4,
    riskReductionScore: 79,
    iconKey: "sat-core-data",
    colorTheme: "neutral",
    flagEnterprise: true,
    flagGovernment: true,
    flagTelco: true,
    flagConsumer: true,
    flagAiAgent: true,
    globalAvailability: true,
    apiReady: true,
    auditRequired: true,
    consentRequired: true,
    zeroKnowledgeCompatible: true,
    simOrEsimRequired: false,
    deviceBindingRequired: false,
  },
  {
    displayOrder: 16,
    protocolCode: "SAT-TRUST",
    protocolSlug: "sat-trust",
    protocolName: "SAT-TRUST",
    protocolCategory: "Trust Engine",
    shortDescription: "Trust scoring, fraud reduction, policy enforcement, and risk analysis.",
    longDescription:
      "SAT-TRUST aggregates signals from device, network, behavior, and third-party intelligence to drive adaptive authentication, step-up prompts, and automated case routing.",
    securityClassification: "HIGH",
    trustLevel: 4,
    riskReductionScore: 83,
    iconKey: "sat-core-trust",
    colorTheme: "yellow",
    flagEnterprise: true,
    flagGovernment: true,
    flagTelco: true,
    flagConsumer: true,
    flagAiAgent: true,
    globalAvailability: true,
    apiReady: true,
    auditRequired: true,
    consentRequired: false,
    zeroKnowledgeCompatible: false,
    simOrEsimRequired: false,
    deviceBindingRequired: false,
  },
  {
    displayOrder: 17,
    protocolCode: "SAT-NOTIFY",
    protocolSlug: "sat-notify",
    protocolName: "SAT-NOTIFY",
    protocolCategory: "Communications",
    shortDescription: "Verified messaging, callbacks, alerts, and secure communications.",
    longDescription:
      "SAT-NOTIFY signs outbound notifications and verifies inbound webhooks so subscribers can trust channel authenticity across SMS, push, email, and partner APIs.",
    securityClassification: "STANDARD",
    trustLevel: 3,
    riskReductionScore: 70,
    iconKey: "sat-core-notify",
    colorTheme: "purple",
    flagEnterprise: true,
    flagGovernment: true,
    flagTelco: true,
    flagConsumer: true,
    flagAiAgent: true,
    globalAvailability: true,
    apiReady: true,
    auditRequired: true,
    consentRequired: true,
    zeroKnowledgeCompatible: false,
    simOrEsimRequired: false,
    deviceBindingRequired: false,
  },
  {
    displayOrder: 18,
    protocolCode: "SAT-RECOVERY",
    protocolSlug: "sat-recovery",
    protocolName: "SAT-RECOVERY",
    protocolCategory: "Recovery & Continuity",
    shortDescription: "Account recovery, SIM swap detection, device replacement, trust restoration.",
    longDescription:
      "SAT-RECOVERY orchestrates high-friction recovery paths with telco collaboration, cooling-off periods, and cryptographic continuity proofs to resist social engineering.",
    securityClassification: "HIGH",
    trustLevel: 4,
    riskReductionScore: 81,
    iconKey: "sat-core-recovery",
    colorTheme: "red",
    flagEnterprise: true,
    flagGovernment: true,
    flagTelco: true,
    flagConsumer: true,
    flagAiAgent: false,
    globalAvailability: true,
    apiReady: true,
    auditRequired: true,
    consentRequired: true,
    zeroKnowledgeCompatible: false,
    simOrEsimRequired: true,
    deviceBindingRequired: true,
  },
  {
    displayOrder: 19,
    protocolCode: "SAT-ADMIN",
    protocolSlug: "sat-admin",
    protocolName: "SAT-ADMIN",
    protocolCategory: "Administration",
    shortDescription: "Enterprise administrative controls, roles, policies, and configuration.",
    longDescription:
      "SAT-ADMIN implements hierarchical administration with separation of duties, just-in-time elevation, and configuration drift detection for multi-tenant SAT deployments.",
    securityClassification: "SOVEREIGN",
    trustLevel: 5,
    riskReductionScore: 87,
    iconKey: "sat-core-admin",
    colorTheme: "zinc",
    flagEnterprise: true,
    flagGovernment: true,
    flagTelco: true,
    flagConsumer: false,
    flagAiAgent: true,
    globalAvailability: true,
    apiReady: true,
    auditRequired: true,
    consentRequired: true,
    zeroKnowledgeCompatible: false,
    simOrEsimRequired: false,
    deviceBindingRequired: true,
  },
  {
    displayOrder: 20,
    protocolCode: "SAT-INTEROP",
    protocolSlug: "sat-interop",
    protocolName: "SAT-INTEROP",
    protocolCategory: "Interoperability",
    shortDescription: "Cross-platform interoperability for governments, banks, telcos, CRM, AI, and enterprise apps.",
    longDescription:
      "SAT-INTEROP defines profiles, trust registries, and federation gateways so SAT identity and events interoperate with GSMA, OIDC, and sector-specific rails without weakening assurance.",
    securityClassification: "ELEVATED",
    trustLevel: 4,
    riskReductionScore: 75,
    iconKey: "sat-core-interop",
    colorTheme: "green",
    flagEnterprise: true,
    flagGovernment: true,
    flagTelco: true,
    flagConsumer: true,
    flagAiAgent: true,
    globalAvailability: true,
    apiReady: true,
    auditRequired: true,
    consentRequired: true,
    zeroKnowledgeCompatible: false,
    simOrEsimRequired: false,
    deviceBindingRequired: false,
  },
];
