/**
 * Builds `src/lib/deployments/worldWireframePaths.generated.ts` from world-countries GeoJSON.
 * Run: npx tsx scripts/generateWorldWireframe.ts
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import countries from "world-countries";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const DATA = path.join(ROOT, "node_modules/world-countries/data");

const VIEW_W = 1000;
const VIEW_H = 500;
const MAX_RING_PTS = 14;

function project(lon: number, lat: number): [number, number] {
  const x = ((lon + 180) / 360) * VIEW_W;
  const y = ((90 - lat) / 180) * VIEW_H;
  return [x, y];
}

function decimateRing(ring: number[][], maxPts: number): number[][] {
  if (ring.length <= maxPts) return ring;
  const out: number[][] = [];
  const step = (ring.length - 1) / (maxPts - 1);
  for (let i = 0; i < maxPts - 1; i++) {
    const idx = Math.round(i * step);
    out.push(ring[idx]!);
  }
  out.push(ring[ring.length - 1]!);
  return out;
}

function ringToD(ring: number[][]): string {
  if (ring.length < 2) return "";
  const pts = decimateRing(ring, MAX_RING_PTS);
  const parts: string[] = [];
  for (let i = 0; i < pts.length; i++) {
    const [lon, lat] = pts[i]!;
    const [x, y] = project(lon, lat);
    parts.push(`${i === 0 ? "M" : "L"}${x.toFixed(1)},${y.toFixed(1)}`);
  }
  parts.push("Z");
  return parts.join("");
}

function geometryToPaths(geom: { type: string; coordinates: unknown }): string[] {
  const out: string[] = [];
  if (geom.type === "Polygon") {
    const coords = geom.coordinates as number[][][];
    const outer = coords[0];
    if (outer?.length) out.push(ringToD(outer));
  } else if (geom.type === "MultiPolygon") {
    const polys = geom.coordinates as number[][][][];
    let best: number[][] | null = null;
    let bestArea = 0;
    for (const poly of polys) {
      const outer = poly[0];
      if (!outer?.length) continue;
      let minX = Infinity,
        minY = Infinity,
        maxX = -Infinity,
        maxY = -Infinity;
      for (const [lo, la] of outer) {
        const [x, y] = project(lo, la);
        minX = Math.min(minX, x);
        minY = Math.min(minY, y);
        maxX = Math.max(maxX, x);
        maxY = Math.max(maxY, y);
      }
      const area = (maxX - minX) * (maxY - minY);
      if (area > bestArea) {
        bestArea = area;
        best = outer;
      }
    }
    if (best?.length) out.push(ringToD(best));
  }
  return out;
}

function main() {
  const paths: Record<string, string> = {};
  const latlng: Record<string, [number, number]> = {};

  for (const c of countries) {
    const iso2 = c.cca2.toUpperCase();
    if (c.latlng?.length === 2) latlng[iso2] = [c.latlng[0], c.latlng[1]];
  }

  const files = fs.readdirSync(DATA).filter((f) => f.endsWith(".geo.json"));
  for (const file of files) {
    const raw = fs.readFileSync(path.join(DATA, file), "utf8");
    let gj: { features?: Array<{ properties?: { cca2?: string }; geometry?: { type: string; coordinates: unknown } }> };
    try {
      gj = JSON.parse(raw) as typeof gj;
    } catch {
      continue;
    }
    const feat = gj.features?.[0];
    const iso2 = feat?.properties?.cca2?.toUpperCase();
    const geom = feat?.geometry;
    if (!iso2 || !geom) continue;
    const ds = geometryToPaths(geom);
    if (ds.length) paths[iso2] = ds.join(" ");
  }

  const outPath = path.join(ROOT, "src/lib/deployments/worldWireframePaths.generated.ts");
  const body = `// Generated by scripts/generateWorldWireframe.ts — do not edit by hand.
export const WORLD_MAP_VIEWBOX_WIRE = "0 0 ${VIEW_W} ${VIEW_H}" as const;

/** ISO2 (uppercase) → simplified SVG path (equirectangular, ${VIEW_W}×${VIEW_H}). */
export const WORLD_COUNTRY_PATHS: Record<string, string> = ${JSON.stringify(paths)};

/** Capital-centroid lat/lng from world-countries when DB coords absent. */
export const WORLD_ISO2_LATLNG: Record<string, readonly [number, number]> = ${JSON.stringify(latlng)};
`;
  fs.writeFileSync(outPath, body, "utf8");
  console.info(`Wrote ${Object.keys(paths).length} paths, ${Object.keys(latlng).length} latlng → ${outPath}`);
}

main();
